# This package contains general purpose javascript libraries, some exclusive to
# the browser or to node, but generally in both if it makes sense.

package(default_visibility = ["//visibility:public"])