package(default_visibility = ["//visibility:public"])

load("//decentraland/c2-data/contracts:solc_contract.bzl", "solc_contract")
load("//decentraland/c2-data/contracts:web3x_codegen.bzl", "web3x_codegen")

solc_contract(name = "Katalyst")
web3x_codegen(name = "Katalyst")