package(default_visibility = ["//visibility:public"])

load(":solc_contract.bzl", "solc_contract")
load(":web3x_codegen.bzl", "web3x_codegen")

solc_contract(name = "Katalyst")
web3x_codegen(name = "Katalyst.lib")